name: minimal

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Echo message
      run: |
        echo "This is a minimal workflow to test GitHub Actions"
        echo "Branch: $GITHUB_REF"
        echo "Repository: $GITHUB_REPOSITORY"